name: C Program Runner

on: 
  push:
  workflow_dispatch:

jobs:
  build-and-run-c:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install GCC
      run: sudo apt-get update && sudo apt-get install build-essential

    - name: Compile C program
      run: gcc -o myprogram sha256.c

    - name: Run C program
      run: ./sha256 > output.txt
      shell: bash

    - name: Upload Result as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: c-program-output
        path: output.txt
