name: C Program Runner

on: 
  push:
  workflow_dispatch:

jobs:
  build-and-run-c:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install GCC
      run: sudo apt-get update && sudo apt-get install build-essential

    - name: Compile C program
      run: gcc -o test test.c -lcrypto -Wno-deprecated-declarations

    - name: Run C program
      run: ./test > output.txt
      shell: bash

    - name: Upload Result as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: c-program-output
        path: output.txt
    - name: 提交更改
      run: |
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git config --local user.email "pantong1995@126.com"
          git config --local user.name “xiaotong1995”
          git add .
          git commit *.txt -m "Add generated file"
          #git pull --rebase
          git push -f  
